fix: deployment

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -24,7 +24,7 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      # Step 4: Run tests
+      # Step 4: Run tests (optional)
       # - name: Run tests
       #   run: npm test
 
@@ -42,7 +42,7 @@ jobs:
             exit 1
           fi
 
-      # Step 7: Add EC2 instance to known hosts to avoid host verification failure
+      # Step 7: Add EC2 instance to known hosts
       - name: Add EC2 to known hosts
         run: |
           mkdir -p ~/.ssh
@@ -56,8 +56,13 @@ jobs:
           AWS_HOST: ${{ secrets.AWS_HOST }}
           AWS_USERNAME: ec2-user
         run: |
-          echo "$AWS_PRIVATE_KEY" > private_key.pem
+          echo "$AWS_PRIVATE_KEY" | base64 --decode > private_key.pem
           chmod 600 private_key.pem
+
+          if [ ! -f private_key.pem ]; then
+            echo "Private key file not found!"
+            exit 1
+          fi
 
           echo "Deploying to EC2 instance..."
           scp -i private_key.pem -r dist package.json package-lock.json $AWS_USERNAME@$AWS_HOST:/home/ec2-user/app
@@ -65,7 +70,7 @@ jobs:
           ssh -i private_key.pem $AWS_USERNAME@$AWS_HOST << 'EOF'
             cd /home/ec2-user/app
             npm ci --omit=dev
-            pm2 restart all || pm2 start "npm run start:prod" --name "my-nestjs-app"
+            pm2 restart all || pm2 start "npm run start:staging" --name "study-english-data-portal"
             exit
           EOF
 
